before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
#snapshot:
#  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^intergration:'
      - '^assets:'
nfpms:
- maintainer: Bisohns Corp.
  description: YAML based tool for monitoring metrics across multiple hosts
  homepage: https://github.com/bisohns/saido
  license: Apache License 2.0
  formats:
    - deb
    - rpm
    - apk
