# Ansible inspired Config
hosts:
  connection:
    # password logging ssh driver
    type: ssh
    username: root 
    password: somethingSecret
  children:
    x.example.net:
    y.example.net:
    z.example.net:
    "192.0.1.5":
      alias: home-server
      connection: 
        type: ssh
        username: root 
        password: somethingSecret
        port: 2222
    "192.0.1.4":
      # local driver
      connection: 
        type: local
    eu-west1:
      # key file logging ssh driver
      connection:
        type: ssh
        private_key_path: /path/to/private/key
        port: 2222
      children:
        "192.0.10.3":
        "192.0.10.5":
    eu-west2:
      # passworded key file logging ssh driver
      connection:
        type: ssh
        private_key_path: /path/to/private/key
        private_key_passphrase: "hexadecimal"
        port: 3333

metrics:
  memory:
  tcp:
  # custom command to show uptime
  custom: "cat /proc/uptime"
poll-interval: 30
