# Ansible inspired Config
hosts:
  children:
    "0.0.0.0":
      alias: home-server
      connection: 
        type: ssh
        username: ci-dev 
        port: 2222
        private_key_path: "/Users/diretnandomnan/Projects/Personal/saido/ssh-key/ci/ci-test-key"
    "127.0.0.1":
      connection: 
        type: local

metrics:
- memory
- tcp
poll-interval: 10
