on: 
  push:
    branches: [ main, develop,feature/test-goreleaser]
  pull_request:
    branches: [ main]
name: Test-Linux
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version:  '>=1.16'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup SSH server and config
        # run docker ssh container for ssh tests
        run: |
          make dependencies
          make build-frontend
          make prep-ci-ssh
      - name: Test
        run: | 
          go mod tidy
          ls /home/runner/work/saido/saido/ssh-key/ci/  
          go test -v ./...
