on: 
  push:
    branches: [ main, develop,feature/test-goreleaser]
  pull_request:
    branches: [ main]
name: Test-MacOs
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version:  '>=1.16'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./web/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache go modules
        id: cache-go-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup config script 
        # using locals for mac-OS because github CI mac platforms don't have docker
        run: | 
          make prep-ci-local
          make dependencies
          make build-frontend
      - name: Test
        run: | 
          go mod tidy  
          go test -v ./...
