on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup SSH server
        # run docker ssh container for ssh tests
        run: |
          sudo mkdir -p /home/runner/.ssh
          echo "${{ secrets.TEST_PUB_KEY }}" >> /home/runner/.ssh/id_rsa.pub
          echo "${{ secrets.TEST_PRIV_KEY }}" >> /home/runner/.ssh/id_rsa
          docker run -d \
          -e PASSWORD_ACCESS=false \
          -e PGID=1000 \
          -e PUID=1000 \
          -e SUDO_ACCESS=false \
          -e USER_NAME=dev \
          -e PUBLIC_KEY_FILE=/root/.ssh/id_rsa.pub \
          -v /home/runner/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
          linuxserver/openssh-server
      - name: Test
        run: go test -v ./...
